### ISSUE TITLE
Issues about the running of "predict_json.py" in example file

### ISSUE THREAD

**Issue by DICPZhou** [CederGroupHub/MatBERT-synthesis-classifier#2]
When I ran this program, I had the following problem：
     Traceback (most recent call last):
  File "/home/dicp2020/Desktop/BERT-project/MatBERT-synthesis-classifier/examples/predict_json.py", line 20, in <module>
    result = run_batch(batch, model, tokenizer)
  File "/home/dicp2020/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/dicp2020/anaconda3/lib/python3.7/site-packages/synthesis_classifier-0.0.1-py3.7.egg/synthesis_classifier/pclassifier.py", line 67, in run_batch
    scores = get_classification_scores(outputs)
  File "/home/dicp2020/anaconda3/lib/python3.7/site-packages/synthesis_classifier-0.0.1-py3.7.egg/synthesis_classifier/pclassifier.py", line 34, in get_classification_scores
    outputs = model_output.cpu().numpy()
AttributeError: 'str' object has no attribute 'cpu'

I am looking forward to your reply, thank you very much!

**Comment by hhaoyan** [comment]
What's the output of `pip list`?

**Comment by hhaoyan** [comment]
If you are using transformers==4.x.x, there is a change of the BERT model outputs from tuples to namedtuples which gives the above error. 

I just pushed a fix that overrides this behavior. The code should work if you pull the latest commit.
